DROP TABLE IF EXISTS users,
businesses;


CREATE TABLE users (
  id INT PRIMARY KEY AUTO_INCREMENT NOT NULL UNIQUE,
  firstName VARCHAR(25) NOT NULL,
  lastName VARCHAR(25) NOT NULL,
  email VARCHAR(25) NOT NULL,
  userName VARCHAR(25) NOT NULL UNIQUE,
  password VARCHAR(25) NOT NULL
);